### ISSUE TITLE
Feature request: Ability change channels during runtime

### ISSUE THREAD

**Issue by ptnexo** [gronxb/hot-updater#502]
By having channel configured only during a native build, I'm not able to test certain hot update before going to production and clients until a new native build is deployed and configured as for example "staging" or "dev". This by the way will create a new fingerprint, therefor fingerprint approach becomes unusable and its also a huge risk when talking about hot updates, addressing specific problem. Someone by mistake can add/remove code to the native build which isn't on the clients devices and things might go south.

IMHO being able to select the channel you want is a must, otherwise something unexpected could happen. Obviously its the developer's responsibility to disable this feature for the production clients or whatever he decides. Having dynamic channel switching also covers beta feature adoption even on production clients. It depends on the use case and what you as a developer decide to do.

Thank you for the great library!

**Comment by ptnexo** [comment]
It turned out this might be relatively easy to accomplish, I'm able to switch channels through the JS code by a simple patch. Once the optional `channel` parameter is added, it could be set in the update policy config. 

The only problem I can see so far (on iOS, havn't tested it on Android) is that if you switch to the latest build from one channel, you cannot switch to an older build from another channel. @gronxb can you give me a hint what I can do to override this behavior?

![Diff Screenshot](https://i.imgur.com/x9wKZwh.png)

**Comment by gronxb** [comment]
It’s relatively easy to switch channels dynamically at runtime, just like you said.
However, the reason I didn’t do it that way is because the workflow would become too complicated.
Feel free to try it that way if you think it’s necessary.

**Comment by oktaysenkan** [comment]
Why do you use `hot-updater.config.ts` to specify the app's `releaseChannel`? I think that `hot-updater.config.ts` must be only related to the CLI. I have multiple environments, and need to specify `releaseChannel` based on a variable.

```
import Config from 'react-native-config';

HotUpdater.wrap({
    source: Config.HOT_UPDATER_SOURCE ?? '',
    releaseChannel: Config.HOT_UPDATER_RELEASE_CHANNEL ?? ''
}}
```

Console Output

```
"process.env.HOT_UPDATER_SOURCE": "https://update.xxx.com/api/check-update"
"react-native-config.HOT_UPDATER_SOURCE": "https://test-update.xxx.com/api/check-update"
```

Now my production app listening `https://test-update.xxx.com/api/check-update` instead of `https://update.xxx.com/api/check-update`. I have fixed it by to push an update to the `test-update` domain

**Comment by gronxb** [comment]
@oktaysenkan 

The `releaseChannel` setting has been removed from `hot-updater.config.ts` in the latest version, and is now delegated to each native app’s configuration.

You can find the updated documentation here:  
https://hot-updater.dev/guide/channel.html

If you check the docs again, you’ll see how this behavior has changed.  
That said, the concept of `releaseChannel` still exists.

The reason is that **setting the initial release channel** is critical.  
In order to establish a "channel-based update flow" within the app, the concept of the *initial channel* must be defined.

What you referred to as `releaseChannel` is essentially the configuration that determines **how the app gets assigned to its initial channel**.

**Comment by gronxb** [comment]
https://github.com/gronxb/hot-updater/releases/tag/v0.26.0

https://hot-updater.dev/docs/guides/runtime-channel-switch
